apiVersion: v1
kind: Service                    
metadata:
  name: api   
  namespace: development
spec:
  type: ClusterIP
  ports:                    
  - name: http
    protocol: TCP
    port: 5000
    targetPort: go-api
  selector:
    app: api     
