apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: api
  namespace: development 
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: api        
  template:                     
    metadata:
      labels:                 
        app: api
    spec:
      hostNetwork: true
      containers:
      - name: api
        image: test-project_backend:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5000
            protocol: TCP 
            name: go-api
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"