apiVersion: v1
kind: Service                    
metadata:
  name: web    
  namespace: development
spec:
  type: NodePort                 
  ports:                         
  - nodePort: 32410
    name: http
    protocol: TCP
    port: 80
    targetPort: go-web
  selector:
    app: web      

                                  